# Plugins
plugins:
- jekyll-sitemap
- jekyll-twitter-plugin
safe: false

title: Alkan Lab Research
description: Combinatorial algorithms, hardware/software co-design, computational genomics from the Alkan lab at the Bilkent University
url: http://bilkentcompgen.github.io

markdown: kramdown
permalink: /:categories/:title/
future: true
sass:
  sass_dir: css

plugins: ['jekyll-twitter-plugin']

exclude:
  - "*.branches"
  - "*.class"
  - "*.cpp"
  - "*.csv"
  - "*.fasta"
  - "*.gz"
  - "*.h"
  - "*.hh"
  - "*.ipynb"
  - "*.jar"
  - "*.java"
  - "*.kml"
  - "*.log"
  - "*.mcc"
  - "*.nb"
  - "*.newick"
  - "*.nex"
  - "*.py"
  - "*.R"
  - "*.rb"
  - "*.Rmd"
  - "*.tiff"
  - "*.tips"
  - "*.trees"
  - "*.tsv"
  - "*.txt"
  - "*.xml"
  - "*.zip"
  - "Gemfile"
  - "Gemfile.lock"

projects:
  
